<?php
$Idioma = array(
    
/* V_Menu */
'Menu Principal' => 'Main Menu',
'Gestionar usuarios' => 'User Management',
'Gestionar roles' => 'Roles Management',
'Gestionar funcionalidades' => 'Functionalities Management',
'Gestionar páginas' => 'Webpages Management',
'Gestionar roles de usuario' => 'User Roles Management',
'Gestionar páginas de usuario' => 'User Webpages Management',

/* comun */
'boton_crear' => 'Create',
'boton_guardar' => 'Save',
'boton_modificar' => 'Modify',
'boton_cancelar' => 'Cancel',
'boton_atras' => 'Back',
'boton_volver' => 'Back',
'Volver' => 'Back',
'boton_menu' => 'Menu',
'boton_si' => 'Yes',
'boton_no' => 'No',
'Buscar' => 'Search',
'Descripción' => 'Description',
'Buscar por Nombre' => 'Search by Name',
'Buscar por Apellido' => 'Search by Last Name',

/* Funcionalidades */
'Funcionalidades' => 'Functionalities',
'Crear nueva funcionalidad' => 'New Functionality',
'Eliminar funcionalidad' => 'Delete Functionality',
'Modificar funcionalidad' => 'Edit Functionality',
'Consultar funcionalidad' => 'Show Functionality',
'Alta Rol' => 'New Role',
'Rol registrado' => 'Role saved',    
'El Rol ya existe' => 'Role already exist in database',    
    
'af_title' => 'Create new functionality',    
'bf_title' => 'Delete functionality',
'confirm_delete_funcionalidad' => 'Are you sure you want to delete this functionality?',

'Funcionalidad' => 'Functionality',
'Nombre de la funcionalidad' => 'Name of the functionality',
'Descripción de la funcionalidad' => 'Description of the functionality',
'Páginas asignadas' => 'Webpages',
'Buscar funcionalidad' => 'Search functionality',
'Funcionalidades asignadas' => 'Linked functionalities',
'Funcionalidad asignada' => 'Linked functionality',
'Alta Funcionalidad' => 'New Functionality',
'Funcionalidad registrada' => 'Functionality saved',
'confirm_delete_funcionalidad' => 'Delete confirmation functionality',
'Descripcion de la funcionalidad' => 'Description of the functionality',
'La funcionalidad ya existe' => 'The functionality already exists',

/* Usuarios */
'Crear nuevo usuario' => 'Create New User',
'Eliminar usuario' => 'Delete User',
'Modificar usuario' => 'Edit User',
'Consultar usuario' => 'Show User',
     
'au_title' => 'Create new user',
'bu_title' => 'Delete user',
'cu_title' => 'Consult user',
'mu_title' => 'Modify user',

'Buscar por nombre' => 'Search by name',
'Buscar por apellidos' => 'Search by last name',
'Alta Usuario' => 'New User',    
'Buscar usuario' => 'Search user',
'Buscar Apellido' => 'Search Last Name',
'Nombre usuario' => 'User First Name',
'Apellidos usuario' => 'User Last Name',
'Email usuario' => 'User Email',
'Calle usuario' => 'User Street',
'Número calle usuario' => 'User Street Number',    
'Localidad usuario' => 'User Location', 
 'Usuario dado de alta' => 'User saved',
'El usuario ya existe' => 'The user already exist in database',
'Confirmar eliminacion usuario' => 'Are you sure you want to delete this user?',
   
/* Páginas */
'Crear nueva página' => 'New webpage',
'Eliminar página' => 'Delete webpage',
'Modificar página' => 'Edit webpage',
'Consultar página' => 'Show webpage',
'Subir página' => 'Upload webpage',
    
'ap_title' => 'Create New Webpage',
'bp_title' => 'Delete Webpage',

'Alta Pagina' => 'New Página',
'La Pagina ya existe' => 'Webpage añready exist in database',    
'Pagina registrada' => 'Webpage saved',
'Buscar página' => 'Search Webpage',
'Buscar por Nombre pagina' => 'Search webpage by name', 
'Paginas disponibles' => 'Available webpages',  
'Paginas asignadas' => 'Assigned webpages', 
'Paginas asignadas a' => 'Webpages assigned to',
'Pagina' => 'Webpage',
'Funcionalidad' => 'Functionality',
'Funcionalidades asignadas' => 'Linked functionality',   
'Funcionalidades rol' => 'Rol functionalities', 
'Nombre de la página' => 'Webpage Name',
'Descripcion de la página' => 'Webpage Description',
'Enlace al archivo' => 'Link to file',
'Enlace' => 'Link',
'Roles' => 'Roles',
'Paginas a asignar' => 'Pages to assign',
'La pagina ya existe' => 'The page already exists',
'confirm_delete_pagina' => 'Are you sure you want to delete this webpage?',
    
/* Roles */
'Crear nuevo rol' => 'New role',
'Eliminar rol' => 'Delete role',
'Modificar rol' => 'Edit role',
'Consultar rol' => 'Show role',
'Rol' => 'Role',
'Nombre del rol' => 'Role Name',
'Descripción del rol' => 'Role Rescription',
'Roles a asignar' => 'Assigning roles',
'Buscar rol' => 'Search Role',
    
'ar_title' => 'New role',
'br_title' => 'Delete role',
'confirm_delete_rol' => 'Are you sure you want to delete this role?',
'El Rol ya existe' => 'The rol already exists',
'Alta Rol' => 'New Rol',
'Roles asignados' => 'Assigned rol',
'Roles disponibles' => 'Available roles',
'Rol registrado' => 'Registered rol',
'Buscar por NombreRol' => 'Search by rol name',

/* Gestionar Role/Usuario */
'Gestionar Rol/Usuarios' => 'Manage user roles',    
'Roles asignados a' => 'Roles assigned to',
'Gestion Roles Usuarios' => 'Manage user roles',
'Relacion modificada' => 'Relation modified',

/* Gestionar Página/Usuario */
'Gestion usuarios paginas' => 'Manage user webpages',
'Gestionar Pagina/Usuarios' => 'Manage user webpages',

/* Upload page */
'Enviar fichero' => 'Send file',

/*Error*/
'Error' => 'Erreur',
'El Usuario no tiene permisos' => 'The user don\'t have permits',

/* Alta */  
'Url' => 'Url',
'Título' => 'Title',    
'Descripción' => 'Description',
'Usuario' => 'Username',
'Usuarios' => 'Users',
'Contraseña' => 'Password',
'Validar' => 'Log In',
'Nombre' => 'Name',
'Nombre2' => 'Name',
'NombrePersona' => 'First Name',
'Apellidos' => 'Last Name',
'Localidad' => 'Location',
'Calle' => 'Street',
'Numero' => 'Number',
'Email' => 'Email',
'Teléfono' => 'Phone Number',
'Password' => 'Password',
'Verificar Contraseña' => 'Verify Password',
'Verificar_Password' => 'Verify Password',
'Repetir Password' => 'Repeat Password',
'Enlace' => 'Link',    
'Url' => 'Url',  
'Login' => 'Login',    
    
/* Otros */
'Error al introducir la password para ese login' => 'An error has ocurred introducing the password for this login',
'Bienvenido' => 'Welcome',
'Ir al login' => 'Go to login page',
'Error, no existe ese login' => 'Error, the login doesn\'t exists',
'Gestión de permisos (Admin)' => 'Access manager (Admin)',
'Cerrar sesión' => 'Close Session',
'Gestión de Usuarios' => 'User Management',
'Gestión de Funcionalidades' => 'Functionalities Management',
'Gestión de Roles' => 'User Groups Management',
'Gestión de Páginas' => 'Webpages Management',
'Gestión de Permisos' => 'Access Management',
'Acerca de' => 'About',
'Los datos se han actualizado' => 'The data has been updated',
'Su password ha sido actualizada' => 'Password has been updated',
'Registro' => 'Register',
'Demo ejemplo para la ET1' => 'ET1 Demo Example',    
'Registrar' => 'Register',
'ya existe en el sistema como usuario registrado' => 'is already registered in the system',
'Ir al Registro' => 'Go to Resgister',
'Ha sido registrado en el sistema el usuario : ' => 'Has been registered in the system the user : ',
'Login' => 'Login'

)
?>
