<?php
$Idioma = array(
    
/* V_Menu */
'Menu Principal' => 'Menu Principal',
'Gestionar usuarios' => 'Gestionar usuarios',
'Gestionar roles' => 'Gestionar roles',
'Gestionar funcionalidades' => 'Gestionar funcionalidades',
'Gestionar páginas' => 'Gestionar páginas',
'Gestionar roles de usuario' => 'Gestionar roles de usuario',
'Gestionar páginas de usuario' => 'Gestionar páginas de usuario',

/* comun */
'boton_crear' => 'Crear',
'boton_menu' => 'Menú',
'boton_cancelar' => 'Cancelar',
'boton_modificar' => 'Modificar',
'Volver' => 'Volver',
'boton_volver' => 'Volver',
'Buscar' => 'Buscar',
'boton_atras' => 'Volver',
'Descripción' => 'Descripción',
'boton_si' => 'SI', 
'boton_no' => 'NO',

/* Funcionalidades */
'Funcionalidades' => 'Funcionalidades',
'Crear nueva funcionalidad' => 'Crear nueva funcionalidad',
'Eliminar funcionalidad' => 'Eliminar funcionalidad',
'Modificar funcionalidad' => 'Modificar funcionalidad',
'Consultar funcionalidad' => 'Consultar funcionalidad',

'af_title' => 'Crear nueva funcionalidad',
'bf_title' => 'Eliminar funcionalidad',

'Funcionalidad' => 'Funcionalidad',
'Nombre de la funcionalidad' => 'Nombre de la funcionalidad',
'Descripción de la funcionalidad' => 'Descripción de la funcionalidad',
'Páginas asignadas' => 'Páginas asignadas',
'Buscar funcionalidad' => 'Buscar funcionalidad',
'Funcionalidades asignadas' => 'Funcionalidades asignadas',
'Funcionalidad asignada' => 'Funcionalidad asignada',
'Alta Funcionalidad' => 'Alta Funcionalidad',
'Funcionalidad registrada' => 'Funcionalidad registrada',
'confirm_delete_funcionalidad' => 'Confirmación eliminación funcionalidad',
'Descripcion de la funcionalidad' => 'Descripción de la funcionalidad',
'La funcionalidad ya existe' => 'La funcionalidad ya existe',
    
/* Usuarios */
'Crear nuevo usuario' => 'Crear nuevo usuario',
'Eliminar usuario' => 'Eliminar usuario',
'Modificar usuario' => 'Modificar usuario',
'Consultar usuario' => 'Consultar usuario',
     
'au_title' => 'Crear nuevo usuario',
'bu_title' => 'Eliminar usuario',
'cu_title' => 'Consultar usuario',
'mu_title' => 'Modificar usuario',
    
'Buscar por nombre' => 'Buscar por nombre',
'Buscar por apellidos' => 'Buscar por apellidos',
'Nombre usuario' => 'Nombre usuario',
'Apellidos usuario' => 'Apellidos usuario',
'Email usuario' => 'Email usuario',
'Calle usuario' => 'Calle usuario',
'Número calle usuario' => 'Número calle usuario',    
'Localidad usuario' => 'Localidad usuario',    
'Usuario dado de alta' => 'Usuario dado de alta',
'Alta Usuario' => 'Alta Usuario',
'El usuario ya existe' => 'El usuario ya existe',
'Confirmar eliminacion usuario' => 'Confirmar eliminación usuario',
    
/* Páginas */
'Crear nueva página' => 'Crear nueva página',
'Eliminar página' => 'Eliminar página',
'Modificar página' => 'Modificar página',
'Consultar página' => 'Consultar página',
    
'ap_title' => 'Crear nueva página',
'bp_title' => 'Eliminar página',
   
'Buscar página' => 'Buscar página',
'Buscar por Nombre pagina' => 'Buscar por nombre pagina',
'Paginas disponibles' => 'Paginas disponibles',
'Paginas asignadas' => 'Paginas asignadas',
'Paginas asignadas a' => 'Paginas asignadas a',
'Funcionalidades asignadas' => 'Funcionalidades asignadas',
'Funcionalidades rol' => 'Funcionalidades rol',    
'Nombre de la página' => 'Nombre de la página',
'Descripcion de la pagina' => 'Descripción de la página',
'Enlace al archivo' => 'Enlace al archivo',
'Enlace' => 'Enlace',
'Roles' => 'Roles',
'Alta Pagina' => 'Alta Pagina',
'Pagina' => 'Pagina',
'Paginas a asignar' => 'Páginas a asignar',
'Pagina registrada' => 'Pagina registrada',
'Paginas disponibles' => 'Páginas disponibles',
'La pagina ya existe' => 'La pagina ya existe',
'confirm_delete_pagina' => 'Confirmacion eliminación página',

/* Roles */
'Crear nuevo rol' => 'Crear nuevo rol',
'Eliminar rol' => 'Eliminar rol',
'Modificar rol' => 'Modificar rol',
'Consultar rol' => 'Consultar rol',
'Nombre del rol' => 'Nombre del rol',
'Descripcion del rol' => 'Descripción del rol',
'Roles a asignar' => 'Roles a asignar',
'Rol' => 'Rol',
'confirm_delete_rol' => 'Confirmación eliminación del rol',
'El Rol ya existe' => 'El Rol ya existe',
'Alta Rol' => 'Alta Rol',
'Roles asignados' => 'Roles asignados',
'Roles disponibles' => 'Roles disponibles',
'Rol registrado' => 'Rol registrado',
'Buscar por NombreRol' => 'Buscar por nombre del rol',
'ar_title' => 'Crear nuevo rol',
'br_title' => 'Eliminar rol',

/* Gestionar Role/Usuario */
'Gestionar Rol/Usuarios' => 'Gestionar Rol/Usuarios',
'Roles asignados a' => 'Roles asignados a',
'Gestion Roles Usuarios' => 'Gestion Roles Usuarios',
'Relacion modificada' => 'Relacion modificada',

/* Gestionar Página/Usuario */
'Gestion usuarios paginas' => 'Gestion Usuarios Paginas',
'Gestionar Pagina/Usuarios' => 'Gestionar Página/Usuarios',

/* Alta */    
'Descripcion' => 'Descripción',
'Usuario' => 'Usuario',
'Validar' => 'Validar',
'Nombre' => 'Nombre',
'Nombre2' => 'Nombre',
'Apellidos' => 'Apellidos',
'Localidad' => 'Localidad',
'Calle' => 'Calle',
'Numero' => 'Numero',
'Email' => 'Email',
'Teléfono' => 'Teléfono',
'Login' => 'Login',
'Password' => 'Password',
'Verificar_Password' => 'Verificar Password',
'Email' => 'E-Mail',
'Enlace' => 'Enlace',    
'Url' => 'Url',  
'Título' => 'Título',  

 /* Otros */
'Error al introducir la password para ese login' => 'Error al introducir la password para ese login',
'Bienvenido' => 'Bienvenido',
'Ir al login' => 'Ir al login',
'Error, no existe ese login' => 'Error, no existe ese login',
'Gestión de permisos (Admin)' => 'Gestión de permisos (Admin)',
'Cerrar sesión' => 'Cerrar la sesión',
'Gestión de Usuarios' => 'Gestión de Usuarios',
'Gestión de Funcionalidades' => 'Gestión de Funcionalidades',
'Gestión de Roles' => 'Gestión de Roles',
'Gestión de Páginas' => 'Gestión de Páginas',
'Gestión de Permisos' => 'Gestión de Permisos',
'Acerca de' => 'Acerca de',
'Los datos se han actualizado' => 'Los datos se han actualizado',
'Su password ha sido actualizada' => 'Su password ha sido actualizada',
'Registro' => 'Registro',
'Demo ejemplo para la ET1' => 'Demo ejemplo para la ET1',
'Registrar' => 'Registrar',
'ya existe en el sistema como usuario registrado' => 'ya existe en el sistema como usuario registrado',
'Ir al Registro' => 'Ir al Registro',
'Ha sido registrado en el sistema el usuario : ' => 'Ha sido registrado en el sistema el usuario : ',
'Login' => 'Identificarse'
)
?>
